export const FILTERS = [
  { key: 'all', label: '전체' },
  { key: 'damo-blog', label: 'DAMO 블로그' },
  { key: 'damo-feed', label: 'DAMO 피드' },
  { key: 'shorts', label: 'Shorts' },
  { key: 'youtube', label: '유튜브' },
  { key: 'blog', label: 'N 블로그' },
  { key: 'news', label: 'N 뉴스' },
  { key: 'cafe', label: 'N 카페' },
  { key: 'shop', label: 'N 쇼핑' },
  { key: 'image', label: 'N 이미지' },
  { key: 'kin', label: '지식iN' },
  { key: 'book', label: 'N 도서' },
  { key: 'webkr', label: 'N 웹' },
  { key: 'kakao-blog', label: 'D 블로그' },
  { key: 'kakao-cafe', label: 'D 카페' },
  { key: 'kakao-web', label: 'D 웹' },
  { key: 'kakao-video', label: 'D 영상' },
  { key: 'kakao-image', label: 'D 이미지' },
  { key: 'reddit', label: 'Reddit' },
  { key: 'instagram', label: 'Instagram' },
];
